### signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "test",
}
header name: header value

### login
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "test",
}
content